workflow:
  rules:
    # Explicitly opt into merge request pipelines.
    # This in turn enables gitlab CI variables that are only
    # set on merge request pipelines (as opposed to the default "push" trigger),
    # such as CI_MERGE_REQUEST_DIFF_BASE_SHA.
    # https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html#add-jobs-to-merge-request-pipelines
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Also run on pushes to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# These variables are set everywhere, unconditionally.
variables:
  TERM: "ansi"
  DEBUG_CI: "yes"

include:
  # Run our clone of tor's CI
  - local: ci/tor-gitlab-ci.yml
    inputs:
      tor-repo: https://gitlab.torproject.org/tpo/core/tor.git
      tor-branch: main
      # main@2024-11-19
      tor-commit: 89e5e03dd535c9b8a8b3a7e40da57145fdd558ba
  - project: tpo/tpa/ci-templates
    file: scripts/apt.yml
    # main@2024-11-19
    ref: c800c775550109d6842756e00a397e02962b3534

# A more stripped-down debian template for tests that aren't specifically
# replicating tor's CI.
.debian-template: &debian-template
  image: containers.torproject.org/tpo/tpa/base-images/debian:bullseye
  tags:
    - amd64
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    # Number of seconds to allow for bootstrap, overriding the default of 60.
    # 120 is what e.g. bootstrap-network.sh uses.
    # Give even a bit more than that since we're not using retries (as test-network.sh does)
    CHUTNEY_START_TIME: 300
    # We generally want debug output, in tests running chutney
    CHUTNEY_DEBUG: 1
  cache:
    key: $CI_JOB_NAME_SLUG-apt
    paths:
      # tpo/tpa/ci-templates's [.apt-init] puts the apt cache here
      - .cache/apt
  before_script:
    # Defined in tpo/tpa/ci-templates
    - !reference [.apt-init]
    # This is where pip installs binaries.
    - export PATH="$PATH:$HOME/.local/bin"
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - net

run-examples:
  <<: *debian-template
  script:
    - apt-get install
        python3
        python3-pip
        tor
    - python3 -m pip install --user .
    - ./examples/use_as_module.py

# Tests the `chutney` script autogenerated by pip,
# which directly invokes TorNet.__main__
chutney-script:
  <<: *debian-template
  script:
    - apt-get install
        python3
        python3-pip
        tor
    - python3 -m pip install --user .

    # Use the chutney wrapper script generated by pip.
    - CHUTNEY="$HOME/.local/bin/chutney"

    # Name of a built-in network
    - NETWORK=basic-min

    - |
      "$CHUTNEY" configure "$NETWORK"
      "$CHUTNEY" start "$NETWORK"
      "$CHUTNEY" wait_for_bootstrap "$NETWORK"
      "$CHUTNEY" verify "$NETWORK"
      "$CHUTNEY" stop "$NETWORK"

unit-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3
  - ./tests/unit-tests.sh

torrc-template-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3-pip
      tor
  # chutney wants to find this executable when testing pt configs, but for this
  # test doesn't actually run it.
  - ln -s /bin/true /usr/local/bin/obfs4proxy
  - python3 -m pip install --user .
  - ./tests/torrc-template-tests

network-config-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3-pip
      tor
  # chutney wants to find this executable when testing pt configs, but for this
  # test doesn't actually run it.
  - ln -s /bin/true /usr/local/bin/obfs4proxy
  - python3 -m pip install --user .
  - ./tests/network-config-tests

# We currently only use shadow in one job, but building it is complex enough
# that it's probably worth putting in its own job.
build-shadow:
  <<: *debian-template
  variables:
    JOB_SHADOW_REPO: "https://github.com/shadow/shadow.git"
    JOB_SHADOW_BRANCH: "main"
    # 2024-12-04
    JOB_SHADOW_COMMIT: "91e94f3"
  artifacts:
    paths:
      - opt/shadow
      - wheels
    # Intended for consumption later in the pipeline; no need to keep them
    # around for longer.
    expire_in: 1 day
  cache:
    - key: V3-$CI_JOB_NAME-shadow-$JOB_SHADOW_COMMIT
      paths:
      - opt/shadow
      - wheels
  tags:
    - amd64
  script:
    # Build shadow
    - |
      if [ -f opt/shadow/bin/shadow ]
      then
        echo "Using shadow binary from cache"
      else
        echo "Building shadow"
        apt-get install git
        git clone --shallow-since=2021-08-01 -b $JOB_SHADOW_BRANCH $JOB_SHADOW_REPO ~/src/shadow
        cd ~/src/shadow
        git checkout $JOB_SHADOW_COMMIT
        export CC=gcc CXX=g++ CONTAINER=debian:bullseye BUILDTYPE=release RUSTPROFILE=minimal
        ci/container_scripts/install_deps.sh
        ci/container_scripts/install_extra_deps.sh
        export PATH="$HOME/.cargo/bin:${PATH}"
        ./setup build --jobs $(nproc) --prefix $CI_PROJECT_DIR/opt/shadow
        ./setup install
        apt-get install -y python3-pip
        mkdir $CI_PROJECT_DIR/wheels
        python3 -m pip wheel --wheel-dir=$CI_PROJECT_DIR/wheels ./shadowtools
      fi

network-config-tests-diff:
  <<: *debian-template
  needs:
  - build-shadow
  tags:
    - amd64
    # Non-TPA runners may not support running shadow.
    - tpa
  # This job fails if there's any diff in output. Often such a diff is expected,
  # though should be reviewed.
  allow_failure: true
  rules:
    # Only run in merge-request pipelines, where CI_MERGE_REQUEST_DIFF_BASE_SHA
    # is defined.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
  - apt-get install
      diffoscope-minimal
      git
      python3-pip
      python3-venv
      tor

  # install shadow
  - apt-get install stow libglib2.0-0
  - mkdir -p "$HOME"/.local
  - stow -d opt -t "$HOME"/.local shadow

  # install shadowtools, for `shadow-exec`
  - python3 -m pip install --user --no-index --find-links=./wheels shadowtools

  # chutney wants to find this executable when testing pt configs, but
  # doesn't actually run it for this test.
  - ln -s /bin/true /usr/local/bin/obfs4proxy

  # install chutney
  - python3 -m pip install --user .

  - ./tests/network-config-tests-diff "$CI_MERGE_REQUEST_DIFF_BASE_SHA"
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - artifacts

shellcheck:
  <<: *debian-template
  script:
  - apt-get install
      shellcheck
  - ./tests/shellcheck-tests.sh

python-lint:
  <<: *debian-template
  variables:
    # Most recent as of 2024-10-24
    BLACK_VERSION: 24.10.0
    # Most recent as of 2024-10-3
    MYPY_VERSION: 1.11.2
    # Most recent as of 2024-10-28
    FLAKE8_VERSION: 7.1.1
  script:
  - apt-get install
      python3
      python3-pip
  # We don't really need chutney itself installed, but we do need
  # its dependencies so that mypy can see their relevant types.
  - python3 -m pip install --user .

  - FAILURES=""

  - python3 -m pip install --user mypy=="$MYPY_VERSION"
  - if ! mypy lib; then FAILURES+=" mypy"; fi

  - python3 -m pip install --user black=="$BLACK_VERSION"
  - if ! black --check --diff lib; then FAILURES+=" black"; fi

  - python3 -m pip install --user flake8=="$FLAKE8_VERSION"
  - if ! flake8 lib; then FAILURES+=" flake8"; fi

  - |
    if [ -n "$FAILURES" ]; then
      echo "Failed linters: $FAILURES";
      exit 1;
    fi
