workflow:
  rules:
    # Explicitly opt into merge request pipelines.
    # This in turn enables gitlab CI variables that are only
    # set on merge request pipelines (as opposed to the default "push" trigger),
    # such as CI_MERGE_REQUEST_DIFF_BASE_SHA.
    # https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html#add-jobs-to-merge-request-pipelines
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Also run on pushes to main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# These variables are set everywhere, unconditionally.
variables:
  TERM: "ansi"
  DEBUG_CI: "yes"

include:
  # Run our clone of tor's CI
  - local: ci/tor-gitlab-ci.yml
    inputs:
      tor-repo: https://gitlab.torproject.org/tpo/core/tor.git
      tor-branch: main
      # main@2024-11-19
      tor-commit: 89e5e03dd535c9b8a8b3a7e40da57145fdd558ba
  - project: tpo/tpa/ci-templates
    file: scripts/apt.yml
    # main@2024-11-19
    ref: c800c775550109d6842756e00a397e02962b3534

# A more stripped-down debian template for tests that aren't specifically
# replicating tor's CI.
.debian-template: &debian-template
  image: containers.torproject.org/tpo/tpa/base-images/debian:bullseye
  tags:
    - amd64
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    # Number of seconds to allow for bootstrap, overriding the default of 60.
    # 120 is what e.g. bootstrap-network.sh uses.
    # Give even a bit more than that since we're not using retries (as test-network.sh does)
    CHUTNEY_START_TIME: 300
    # We generally want debug output, in tests running chutney
    CHUTNEY_DEBUG: 1
  cache:
    key: $CI_JOB_NAME_SLUG-apt
    paths:
      # tpo/tpa/ci-templates's [.apt-init] puts the apt cache here
      - .cache/apt
  before_script:
    # Defined in tpo/tpa/ci-templates
    - !reference [.apt-init]
    # This is where pip installs binaries.
    - export PATH="$PATH:$HOME/.local/bin"
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - net

run-examples:
  <<: *debian-template
  script:
    - apt-get install
        python3
        python3-pip
        tor
    - python3 -m pip install --user .
    - ./examples/use_as_module.py

# Tests the `chutney` script autogenerated by pip,
# which directly invokes TorNet.__main__
chutney-script:
  <<: *debian-template
  script:
    - apt-get install
        python3
        python3-pip
        tor
    - python3 -m pip install --user .

    # Use the chutney wrapper script generated by pip.
    - CHUTNEY="$HOME/.local/bin/chutney"

    # Name of a built-in network
    - NETWORK=basic-min

    - |
      "$CHUTNEY" configure "$NETWORK"
      "$CHUTNEY" start "$NETWORK"
      "$CHUTNEY" wait_for_bootstrap "$NETWORK"
      "$CHUTNEY" verify "$NETWORK"
      "$CHUTNEY" stop "$NETWORK"

unit-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3
  - ./tests/unit-tests.sh

torrc-template-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3-pip
      tor
  # chutney wants to find this executable when testing pt configs, but for this
  # test doesn't actually run it.
  - ln -s /bin/true /usr/local/bin/obfs4proxy
  - python3 -m pip install --user .
  - ./tests/torrc-template-tests

network-config-tests:
  <<: *debian-template
  script:
  - apt-get install
      python3-pip
      tor
  # chutney wants to find this executable when testing pt configs, but for this
  # test doesn't actually run it.
  - ln -s /bin/true /usr/local/bin/obfs4proxy
  - python3 -m pip install --user .
  - ./tests/network-config-tests

shellcheck:
  <<: *debian-template
  script:
  - apt-get install
      shellcheck
  - ./tests/shellcheck-tests.sh

python-lint:
  <<: *debian-template
  variables:
    # Most recent as of 2024-10-24
    BLACK_VERSION: 24.10.0
    # Most recent as of 2024-10-3
    MYPY_VERSION: 1.11.2
    # Most recent as of 2024-10-28
    FLAKE8_VERSION: 7.1.1
  script:
  - apt-get install
      python3
      python3-pip
  # We don't really need chutney itself installed, but we do need
  # its dependencies so that mypy can see their relevant types.
  - python3 -m pip install --user .

  - FAILURES=""

  - python3 -m pip install --user mypy=="$MYPY_VERSION"
  - if ! mypy lib; then FAILURES+=" mypy"; fi

  - python3 -m pip install --user black=="$BLACK_VERSION"
  - if ! black --check --diff lib; then FAILURES+=" black"; fi

  - python3 -m pip install --user flake8=="$FLAKE8_VERSION"
  - if ! flake8 lib; then FAILURES+=" flake8"; fi

  - |
    if [ -n "$FAILURES" ]; then
      echo "Failed linters: $FAILURES";
      exit 1;
    fi
