[build-system]
requires = [
  # installation backend
  "setuptools>=61.0",
  # plugin to include all version controlled files
  # under the module directory (./lib) as resources.
  "setuptools_scm>=8"
]
build-backend = "setuptools.build_meta"

[project]
name = "chutney"
version = "0.0.1"
authors = [
  { name="The Tor Project" },
]
description = "A tool for building local testing Tor networks"
readme = "README.md"
# Oldest tested version (default on debian bullseye).
# May or may not work on older versions.
requires-python = ">=3.9.2"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://gitlab.torproject.org/tpo/core/chutney"
Issues = "https://gitlab.torproject.org/tpo/core/chutney/-/issues/"

[tool.setuptools]
# module root is under `lib` (instead of the default of `src`)
package-dir = {"" = "lib"}
