[build-system]
requires = [
  # installation backend
  "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "chutney"
version = "0.0.1"
authors = [
  { name="The Tor Project" },
]
description = "A tool for building local testing Tor networks"
readme = "README.md"
# Oldest tested version (default on debian bullseye).
# May or may not work on older versions.
requires-python = ">=3.9.2"
# Strings from https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    # Mostly intended for internal use in the Tor Project, and quite unstable.
    "Private :: Do Not Upload",
]
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://gitlab.torproject.org/tpo/core/chutney"
Issues = "https://gitlab.torproject.org/tpo/core/chutney/-/issues/"

[project.scripts]
chutney = "chutney.TorNet:__main__"

[tool.setuptools]
# module root is under `lib` (instead of the default of `src`)
package-dir = {"" = "lib"}

[tool.setuptools.packages.find]
# root of where to look for resource files.
# Files must also be specified in MANIFEST.in to actually be included.
where = ["lib"]
