[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chutney"
version = "0.0.1"
authors = [
  { name="The Tor Project" },
]
description = "A tool for building local testing Tor networks"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://gitlab.torproject.org/tpo/core/chutney"
Issues = "https://gitlab.torproject.org/tpo/core/chutney/-/issues/"

[tool.setuptools]
package-dir = {"" = "lib"}
