#!/usr/bin/env python3

# Tests that all of chutney's built-in network configurations can be configured.
#
# This could be done a little more nicely using chutney as a module, but using
# the command-line interface isn't too bad, and tests a bit more end-to-end.
#
# Going through the `configure` step is sufficient to exercise that chutney
# generates at least legal configuration files. Going further (e.g. starting the
# network and waiting for bootstrap) would add substantial run time and
# potential flakiness.

import glob
import os
import subprocess
import sys

from pathlib import Path


def max_config_phase(network_name: str) -> int:
    prefix = "CHUTNEY_CONFIG_PHASES="
    output = subprocess.check_output(
        ["chutney", "print_phases", network_name], text=True
    )
    for line in output.splitlines():
        if line.startswith(prefix):
            return int(line.removeprefix(prefix))
    print("Couldn't parse print_phases output: ", output)
    sys.exit(1)


network_names = [Path(s).name for s in glob.glob("lib/chutney/data/networks/*")]
# Use a consistent order, instead of the arbitrary order returned by glob.
network_names.sort()
# Verify that an arbitrary one is present, to validate that the above glob gave
# us something like what we expect.
assert "basic-min" in network_names

base_data_dir=os.environ.get("CHUTNEY_DATA_DIR", "net")

for network_name in network_names:
    print("Testing network:", network_name)
    for phase in range(1, max_config_phase(network_name) + 1):
        print("Configure phase:", phase)

        env = dict(os.environ)
        env["CHUTNEY_CONFIG_PHASE"] = str(phase)
        # Needed for mixed+hs-v3[-ipv6]; ignored for others.
        env["CHUTNEY_OLD_TOR"] = env.get("CHUTNEY_TOR", "tor")
        # Needed for networks with pluggable transports.
        env["CHUTNEY_TOR_SANDBOX"] = "0"
        # Put output into a directory named after the network, for easier
        # debugging.
        env["CHUTNEY_DATA_DIR"] = f"{base_data_dir}/{network_name}"

        # Flush to avoid child process output appearing out of order
        sys.stdout.flush()
        sys.stderr.flush()

        subprocess.check_call(["chutney", "configure", network_name], env=env)
