#!/usr/bin/env python3

import glob
import subprocess
import sys
import textwrap

from chutney import TorNet
from chutney.TorNet import NodeConfig
from pathlib import Path

network = TorNet.Network()

# Generate configs for all torrc templates, using their legacy names.
configs = [
    NodeConfig(
        torrc="authority-orport-v6.tmpl",
        tag="a",
        authority=True,
        relay=True,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="authority.tmpl",
        tag="a",
        authority=True,
        relay=True,
    ),
    NodeConfig(
        torrc="bridgeauthority.tmpl",
        tag="ba",
        authority=True,
        relay=True,
        bridgeauthority=True,
    ),
    NodeConfig(
        torrc="bridgeclient-obfs4.tmpl",
        tag="bc",
        client=True,
        bridgeclient=True,
        pt_transport="obfs4",
        # Managed proxies are incompatible with sandboxing
        sandbox=False,
    ),
    NodeConfig(
        torrc="bridgeclient.tmpl",
        tag="bc",
        client=True,
        bridgeclient=True,
        # Managed proxies are incompatible with sandboxing
        sandbox=False,
    ),
    NodeConfig(
        torrc="bridge-obfs4.tmpl",
        tag="br",
        bridge=True,
        pt_bridge=True,
        relay=True,
        pt_transport="obfs4",
        # Managed proxies are incompatible with sandboxing
        sandbox=False,
    ),
    NodeConfig(
        torrc="bridge.tmpl",
        tag="br",
        bridge=True,
        relay=True,
    ),
    NodeConfig(
        torrc="bridge-v6.tmpl",
        tag="br",
        bridge=True,
        relay=True,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="client_bwscanner.tmpl",
        tag="c",
        client=True,
        use_microdescriptors=False,
        extra_raw_torrc=textwrap.dedent(
            """
            UseEntryGuards 0
            FetchDirInfoEarly 1
            FetchDirInfoExtraEarly 1
            FetchUselessDescriptors 1
            LearnCircuitBuildTimeout 0
            CircuitBuildTimeout 60
            ConnectionPadding 0
            __DisablePredictedCircuits 1
            __LeaveStreamsUnattached 1
            """
        )
    ),
    NodeConfig(
        torrc="client-only-v6-md.tmpl",
        tag="c",
        client=True,
        ip=None,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="client-only-v6.tmpl",
        tag="c",
        client=True,
        ip=None,
        ipv6_addr="[::1]",
        use_microdescriptors=False,
    ),
    NodeConfig(
        torrc="client.tmpl",
        tag="c",
        client=True,
    ),
    NodeConfig(
        torrc="hs-v3-only-v6-md.tmpl",
        tag="h",
        hs=True,
        ip=None,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="hs-v3-only-v6.tmpl",
        tag="h",
        hs=True,
        ip=None,
        ipv6_addr="[::1]",
        use_microdescriptors=False,
    ),
    NodeConfig(
        torrc="hs-v3.tmpl",
        tag="h",
        hs=True,
    ),
    NodeConfig(
        torrc="relay-MAB.tmpl",
        tag="relay1mbyteMAB",
        relay=True,
        exit=True,
    ),
    NodeConfig(
        torrc="relay-MBR.tmpl",
        tag="relay1mbyteMBR",
        relay=True,
        exit=True,
        extra_raw_torrc=textwrap.dedent(
            """
            Nickname relay1mbyteMBR
            RelayBandwidthRate 1 MBytes
            """
        )
    ),
    NodeConfig(
        torrc="relay-non-dir.tmpl",
        tag="r",
        relay=True,
        exit=True,
    ),
    NodeConfig(
        torrc="relay-non-exit.tmpl",
        tag="r",
        relay=True,
        exit=False,
    ),
    NodeConfig(
        torrc="relay-exit-v6-only.tmpl",
        tag="r",
        relay=True,
        exit=True,
        # XXX clear ip?
        # do we really support v6-only exits?
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="relay-orport-v6-non-exit.tmpl",
        tag="r",
        relay=True,
        exit=False,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="relay.tmpl",
        tag="r",
        relay=True,
        exit=True,
    ),
    NodeConfig(
        torrc="relay-v6.tmpl",
        tag="r",
        relay=True,
        exit=True,
        ipv6_addr="[::1]",
    ),
    NodeConfig(
        torrc="single-onion-v3.tmpl",
        tag="h",
        hs=True,
        hs_singlehop=True,
    ),
    NodeConfig(
        torrc="single-onion-v3-only-v6-md.tmpl",
        tag="h",
        hs=True,
        ip=None,
        ipv6_addr="[::1]",
        hs_singlehop=True,
    ),
]

# Add the configs to the network, getting their corresponding Nodes.
nodes = network.addNodes(configs)
# Configure the network, generating the torrc files.
network.configure()


def template_to_basename(s: str) -> str:
    """Map a legacy template name to  the basename of the python file implementing it"""
    return s.translate({ord("."): "_", ord("-"): "_"}) + ".py"


checked_template_basenames: set[str] = {
    template_to_basename(n.torrc) for n in nodes
}
all_template_basenames: set[str] = {
    Path(s).name for s in glob.glob("lib/chutney/torrc_templates/*_tmpl.py")
}
missed_template_basenames = all_template_basenames.difference(checked_template_basenames)

if len(missed_template_basenames) > 0:
    unhandled = list(missed_template_basenames)
    unhandled.sort()
    print("ERROR: didn't test:")
    for basename in unhandled:
        print("  ", basename)
    sys.exit(1)

print("Passed")
